Repository praveenscience/Internship-LMS-FrontEnd, pull requests merged in 2021-03, with the labels that each got.

#71 Update README.md
  README.md
Labels: Level0, gssoc21

#80 Added intro pitch
  ReadMe.md
Labels: Level1, documentation, gssoc21

#82 Trailer Information for GSSoC.
  ReadMe.md
Labels: Level0, documentation, gssoc21

#91 Adding the methodology section
  ReadMe.md
Labels: Level0, documentation, gssoc21

#96 Contribution steps improved
  Contributing.md
  imagesContributing/Step1.png
  imagesContributing/Step10.png
  imagesContributing/Step12.png
  imagesContributing/Step13.png
  imagesContributing/Step14.png
  imagesContributing/Step15.png
  imagesContributing/Step16.png
  imagesContributing/Step17.png
  imagesContributing/Step2.png
  imagesContributing/Step3.png
  imagesContributing/Step4.png
  imagesContributing/Step5.png
  imagesContributing/Step6.png
  imagesContributing/Step8.png
  imagesContributing/Step9.png
Labels: Level1, documentation, gssoc21

#97 ReadMe: Added Code of Conduct Section
  Code_of_Conduct.md
  ReadMe.md
Labels: Level0, documentation, gssoc21

#98 FAQs added
  ReadMe.md
Labels: Level0, documentation, gssoc21
