Repository praveenscience/Internship-LMS-FrontEnd, pull requests merged in 2021-01, with the labels that each got.

#2 Created Documentation.md
  Documentation.md
Labels: documentation, dwoc, easy

#8 ADDED ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: Level-1, dwoc, easy, swoc

#12 Updated the coc
  Code_of_Conduct.md
Labels: Level-1, documentation, dwoc, easy, swoc

#14 Fix typo in ReadMe.md
  ReadMe.md
Labels: Level-1, documentation, dwoc, easy, swoc

#19 Added config file for Welcome BOT
  .github/config.yml
Labels: Level-2, dwoc, easy, swoc

#16 added pr template
  .github/pull_request_template.md
Labels: Level-1, beginner, dwoc, enhancement, swoc

#22 Updated Readme
  ReadMe.md
Labels: Level-1, documentation, dwoc, easy, swoc
