Repository praveenscience/Internship-LMS-FrontEnd, pull requests merged in 2021-02, with the labels that each got.

#31 Update Auto-Assign Feature
  .github/workflows/action.yml
  .github/workflows/reviewer_auto_assigner.yml
Labels: Level-1, dwoc

#32 Created an MIT License
  LICENSE
Labels: Level-1, dwoc

#17 Header added
  client/package-lock.json
  client/package.json
  client/src/components/App.js
  client/src/components/Header/Header.js
  client/src/styles/App.scss
  client/src/styles/Header/Header.scss
Labels: Level-2, dwoc, easy, swoc

#37 Added issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Level-1, dwoc

#39 Updated README.md with contributors images, CONTRIBUTING.md link
  CONTRIBUTING.md
  README.md
Labels: Level-1, documentation, dwoc
