Repository praveenscience/Internship-LMS-FrontEnd, pull requests merged in 2021-04, with the labels that each got.

#103 Implemented husky for the project
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  client/.eslintignore
  client/.eslintrc.js
  client/.prettierignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/components/Bootstrap/Header.js
  client/src/tests/App.test.js
  package-lock.json
  package.json
Labels: Level3, enhancement, gssoc21

#101 Added more details for FAQs.
  ReadMe.md
Labels: Level0, documentation, gssoc21

#105 Update ReadMe.md
  ReadMe.md
Labels: Level0, documentation, gssoc21

#85 Contribution Steps Added.
  Contributing.md
  docs/Step1.png
  docs/Step10.png
  docs/Step12.png
  docs/Step13.png
  docs/Step14.png
  docs/Step15.png
  docs/Step16.png
  docs/Step17.png
  docs/Step2.png
  docs/Step3.png
  docs/Step4.png
  docs/Step5.png
  docs/Step6.png
  docs/Step7.png
  docs/Step8.png
  docs/Step9.png
  imagesContributing/Step10.png
  imagesContributing/Step12.png
  imagesContributing/Step13.png
  imagesContributing/Step5.png
  imagesContributing/Step6.png
  imagesContributing/Step8.png
  imagesContributing/Step9.png
Labels: Level0, documentation, gssoc21

#110 Design
  design.md
  flowchart/flowchart.jpg
Labels: Design, Level1, gssoc21

#113 Design-user
  design-user.md
  designs/Landing Page.png
  designs/Learning page.png
  designs/Login page copy.png
  designs/User Dashboard copy.png
  designs/User Profile.png
  designs/Welcome Page copy.png
  designs/forget password .png
  designs/help screen.png
Labels: Design, Level2, documentation, gssoc21
